// Egyptian-gym names for the English catalogue. Longest phrases first so
// "lateral pulldown" becomes سحب جانبي instead of جانبي سحب.

const PHRASES = [
  ['captains chair', 'كرسي الكابتن'],
  ['good morning', 'جود مورنينج'],
  ['mountain climber', 'متسلق الجبل'],
  ['lateral pulldown', 'سحب جانبي'],
  ['close grip', 'قبضة ضيقة'],
  ['wide grip', 'قبضة واسعة'],
  ['neutral grip', 'قبضة محايدة'],
  ['overhand grip', 'قبضة من فوق'],
  ['underhand grip', 'قبضة من تحت'],
  ['reverse grip', 'قبضة معكوسة'],
  ['mixed grip', 'قبضة مختلطة'],
  ['bench press', 'بنش برس'],
  ['chest press', 'ضغط صدر'],
  ['shoulder press', 'ضغط كتف'],
  ['military press', 'ضغط عسكري'],
  ['overhead press', 'ضغط فوق الراس'],
  ['calf raise', 'رفع التوأم'],
  ['calf raises', 'رفع التوأم'],
  ['front raise', 'رفع أمامي'],
  ['lateral raise', 'رفع جانبي'],
  ['rear delt', 'خلف الكتف'],
  ['face pull', 'فيس بول'],
  ['pull up', 'عقلة'],
  ['pull ups', 'عقلة'],
  ['chin up', 'عقلة قبضة معكوسة'],
  ['chin ups', 'عقلة قبضة معكوسة'],
  ['sit up', 'سيت أب'],
  ['sit ups', 'سيت أب'],
  ['push up', 'ضغط'],
  ['push ups', 'ضغط'],
  ['push down', 'دفع لأسفل'],
  ['kick back', 'كيك باك'],
  ['dead bug', 'ديد بغ'],
  ['dead lift', 'ديدليفت'],
  ['hip thrust', 'دفع الورك'],
  ['leg press', 'ضغط رجل'],
  ['leg curl', 'كيرل رجل'],
  ['leg extension', 'مد الرجل'],
  ['preacher curl', 'كيرل بريشر'],
  ['concentration curl', 'كيرل تركيز'],
  ['hammer curl', 'كيرل مطرقة'],
  ['wrist curl', 'كيرل رسغ'],
  ['skull crusher', 'سكل كراشر'],
  ['triceps extension', 'مد التراي'],
  ['tricep extension', 'مد التراي'],
  ['biceps curl', 'كيرل باي'],
  ['bicep curl', 'كيرل باي'],
  ['upright row', 'تجديف قائم'],
  ['bent over', 'ميل القدام'],
  ['seated row', 'تجديف جالس'],
  ['one arm', 'ذراع واحدة'],
  ['single arm', 'ذراع واحدة'],
  ['single leg', 'رجل واحدة'],
  ['one leg', 'رجل واحدة'],
  ['per side', 'لكل جانب'],
  ['body weight', 'وزن الجسم'],
  ['resistance band', 'استك مقاومة'],
  ['medicine ball', 'ميدسن بول'],
  ['stability ball', 'كرة توازن'],
  ['bosu ball', 'كرة بوسو'],
  ['ez barbell', 'بار EZ'],
  ['ez bar', 'بار EZ'],
  ['trap bar', 'تراب بار'],
  ['smith machine', 'سميث'],
  ['cable machine', 'ماكينة كيبل'],
  ['leverage machine', 'ماكينة رافعة'],
  ['stationary bike', 'عجلة ثابتة'],
  ['upper body', 'الجزء العلوي'],
  ['lower body', 'الجزء السفلي'],
  ['high pulley', 'بكرة عالية'],
  ['low pulley', 'بكرة واطية'],
  ['behind neck', 'ورا الرقبة'],
  ['behind the', 'ورا'],
  ['on knees', 'على الركبتين'],
  ['on floor', 'على الأرض'],
  ['to chest', 'للصدر'],
  ['to head', 'للراس'],
  ['3/4', 'ثلاثة أرباع'],
  ['45°', '٤٥ درجة'],
  ['45 degrees', '٤٥ درجة'],
]

const WORDS = {
  dumbbell: 'دمبل', dumbbells: 'دمبل', barbell: 'بار', cable: 'كيبل',
  kettlebell: 'كتل بل', band: 'استك', smith: 'سميث', lever: 'رافعة',
  machine: 'ماكينة', rope: 'حبل', roller: 'رولر', wheel: 'عجلة',
  sled: 'زلاجة', sledge: 'زلاجة', hammer: 'همر', bosu: 'بوسو',
  olympic: 'أوليمبي', trap: 'تراب', tire: 'كفر', towel: 'فوطة',
  medicine: 'ميدسن', stability: 'توازن', resistance: 'مقاومة',
  assisted: 'بمساعدة', weighted: 'بوزن', bodyweight: 'وزن الجسم',
  ez: 'EZ', sz: 'SZ',
  curl: 'كيرل', curls: 'كيرل', press: 'ضغط', presses: 'ضغط',
  row: 'تجديف', raise: 'رفع', raises: 'رفع', squat: 'سكوات', squats: 'سكوات',
  squatting: 'سكوات', lunge: 'اندفاع', fly: 'فتح', flyes: 'فتح',
  pulldown: 'سحب لأسفل', pullover: 'بول أوفر', pull: 'سحب',
  push: 'دفع', pushdown: 'دفع لأسفل', dip: 'ديب', dips: 'ديب',
  crunch: 'كرانش', crunches: 'كرانش', extension: 'مد',
  stretch: 'إطالة', shrug: 'shrug', bridge: 'كوبري',
  twist: 'لف', twists: 'لف', twisting: 'لف', twisted: 'ملفوف',
  rotation: 'دوران', rotational: 'دوراني', rotate: 'لف',
  deadlift: 'ديدليفت', snatch: 'خطف', clean: 'كلين', jerk: 'جيرك',
  swing: 'مرجحة', thruster: 'ثراستر', slam: 'ضرب',
  plank: 'بلانك', planche: 'بلانش', hyperextension: 'مد زائد',
  abduction: 'تبعيد', adduction: 'تقريب', abductor: 'مبعِد', adductor: 'مقرِّب',
  flexion: 'ثني', flexor: 'ثناي',
  jump: 'قفز', jumps: 'قفز', kick: 'ركلة', kicks: 'ركلة', kickback: 'كيك باك',
  kickbacks: 'كيك باك', walk: 'مشي', walking: 'مشي', run: 'جري',
  climb: 'تسلق', crawl: 'زحف', throw: 'رمي', tap: 'لمسة',
  hang: 'تعليق', hanging: 'معلّق', lift: 'رفع', lifting: 'رفع',
  carry: 'حمل', hug: 'حضن', squeeze: 'عصر', pass: 'تمرير',
  sit: 'جلوس', seated: 'جالس', sitted: 'جالس', standing: 'واقف',
  lying: 'نائم', kneeling: 'جاثي', prone: 'على البطن', supine: 'على الظهر',
  inverted: 'مقلوب', suspended: 'معلّق', reclining: 'مائل للخلف',
  elevated: 'مرتفع', raised: 'مرفوع', supported: 'مدعوم',
  incline: 'مائل لفوق', decline: 'مائل لتحت', flat: 'مسطح',
  reverse: 'معكوس', reversed: 'معكوس', revers: 'معكوس',
  alternate: 'متناوب', alternating: 'متناوب',
  close: 'ضيق', closer: 'أضيق', wide: 'واسع', narrow: 'ضيق',
  high: 'عالي', low: 'واطي', lower: 'أسفل', upper: 'أعلى',
  inner: 'داخلي', outer: 'خارجي', inside: 'جوا', outside: 'برا',
  front: 'أمامي', rear: 'خلفي', back: 'ظهر', side: 'جانبي',
  lateral: 'جانبي', vertical: 'عمودي', horizontal: 'أفقي',
  straight: 'مستقيم', bent: 'مثني', parallel: 'متوازي',
  overhead: 'فوق الراس', upright: 'قائم', forward: 'قدام',
  backward: 'ورا', downward: 'لتحت', upward: 'لفوق',
  behind: 'ورا', under: 'تحت', above: 'فوق', against: 'ضد',
  through: 'خلال', between: 'بين', around: 'حوالين', across: 'بالعرض',
  over: 'فوق', off: 'من', into: 'لجوه', from: 'من', of: 'من',
  with: 'بـ', on: 'على', in: 'في', to: 'لـ', and: 'و', the: 'ال',
  a: '',
  arm: 'ذراع', arms: 'ذراعين', leg: 'رجل', legs: 'رجلين',
  knee: 'ركبة', knees: 'ركبتين', wrist: 'رسغ', wrists: 'رسغ',
  hand: 'إيد', hands: 'إيد', finger: 'صباع',
  chest: 'صدر', shoulder: 'كتف', neck: 'رقبة', hip: 'ورك',
  glute: 'أرداف', glutes: 'أرداف', gluteus: 'أرداف', butt: 'أرداف',
  calf: 'توأم', calves: 'توأم', hamstring: 'خلف الفخذ', ham: 'خلف الفخذ',
  quad: 'أمام الفخذ', quads: 'أمام الفخذ', quadriceps: 'أمام الفخذ',
  triceps: 'تراي', tricep: 'تراي', biceps: 'باي', bicep: 'باي',
  delt: 'كتف', deltoid: 'كتف', lat: 'لاتس',
  abs: 'بطن', ab: 'بطن', abdominal: 'بطن', oblique: 'جانب',
  spine: 'عمود فقري', scapula: 'لوح الكتف', scapular: 'لوح الكتف',
  pectoralis: 'صدر', pec: 'صدر', groin: 'أعلى الفخذ',
  ankle: 'كاحل', ankles: 'كاحل', toe: 'صباع الرجل', feet: 'قدم',
  head: 'راس', elbow: 'كوع', heel: 'كعب',
  grip: 'قبضة', gripless: 'من غير قبضة',
  overhand: 'من فوق', underhand: 'من تحت',
  pronated: 'كابّة', supinated: 'مقلوبة', pronate: 'كابّة',
  pronation: 'كبّ', supination: 'قلب',
  palms: 'بطن الإيد', palm: 'بطن الإيد',
  bench: 'بنش', benches: 'بنش', floor: 'أرض', wall: 'حيط',
  chair: 'كرسي', box: 'صندوق', cage: 'قفص', pad: 'وسادة',
  bar: 'بار', bars: 'عقلة', attachment: 'وصلة', handle: 'قبضة',
  pulley: 'بكرة', platform: 'منصة', board: 'لوح', rack: 'رف',
  pin: 'مسمار', straps: 'أحزمة', strap: 'حزام',
  ball: 'كرة', bike: 'عجلة',
  exercise: 'تمرين', stretch: 'إطالة', motion: 'حركة',
  pose: 'وضع', position: 'وضع', stance: 'وقفة',
  support: 'سند', balance: 'توازن', stabilization: 'ثبات',
  isometric: 'ثابت', dynamic: 'متحرك',
  full: 'كامل', half: 'نص', quarter: 'ربع',
  single: 'فردي', double: 'مزدوج', twin: 'توأم',
  two: 'اتنين', three: 'تلاتة', both: 'الاتنين',
  one: 'واحد',
  left: 'شمال',
  male: '', female: '',
  pov: '',
  concentration: 'تركيز', preacher: 'بريشر', peacher: 'بريشر',
  spider: 'سبايدر', zottman: 'زوتمان', arnold: 'أرنولد',
  french: 'فرنساوي',
  russian: 'روسي', romanian: 'روماني', bulgarian: 'بلغاري',
  sumo: 'سومو', pistol: 'فردي', goblet: 'كأس',
  zercher: 'زرشر', pendlay: 'بندلاي', jefferson: 'جيفرسون',
  bradford: 'برادفورد', landmine: 'لاندماين', pallof: 'بالوف',
  cuban: 'كوبي', maltese: 'مالطي',
  turkish: 'تركي', hindu: 'هندي', korean: 'كوري',
  judo: 'جودو', boxing: 'ملاكمة',
  archer: 'رامي', donkey: 'حمار', frog: 'ضفدع',
  pike: 'بايك', tuck: 'تك', jack: 'جمبنج جاكس',
  burpee: 'بيربي',
  windmill: 'طاحونة', superman: 'سوبرمان',
  inchworm: 'دودة', handstand: 'وقوف على الإيدين',
  cocoons: 'شرنقة', crab: 'كابوريا',
  butterfly: 'فراشة', bear: 'دب', stork: 'لقلاق',
  skater: 'متزلج', swimmer: 'سباح',
  climber: 'متسلق', mountain: 'جبل',
  skull: 'سكل', crusher: 'كراشر', skullcrusher: 'سكل كراشر',
  pulldowns: 'سحب لأسفل',
  pushup: 'ضغط', situp: 'سيت أب',
  rollerout: 'رول آوت', rollerer: 'رولر',
  cross: 'عبور', crossover: 'كروس أوفر', crossovers: 'كروس أوفر',
  split: 'سبليت', step: 'خطوة', stepbox: 'ستيب',
  jump: 'قفز', plyo: 'بلايوس',
  clean: 'كلين',
  military: 'عسكري',
  decline: 'مائل لتحت',
  incline: 'مائل لفوق',
  seated: 'جالس',
  standing: 'واقف',
  lying: 'نائم',
  kneeling: 'على الركبة',
  hanging: 'معلّق',
  inverse: 'معكوس', inverted: 'مقلوب',
  narrow: 'ضيق',
  wide: 'واسع',
  close: 'ضيق',
  hammer: 'مطرقة',
  preacher: 'بريشر',
  concentration: 'تركيز',
  triceps: 'تراي',
  biceps: 'باي',
  chest: 'صدر',
  back: 'ظهر',
  shoulder: 'كتف',
  rear: 'خلفي',
  front: 'أمامي',
  side: 'جانب',
  lateral: 'جانبي',
  overhead: 'فوق الراس',
  decline: 'مائل لتحت',
  twist: 'لفّة',
  crunch: 'كرانش',
  sit: 'جلوس',
  up: '', ups: '', down: 'أسفل',
  v: 'V', t: 'T', w: 'W', y: 'Y', l: 'L',
  '2': '٢', '3': '٣', '8': '٨', '45': '٤٥',
  '180': '١٨٠', '360': '٣٦٠',
  degrees: 'درجة',
  '°': 'درجة',
  body: 'جسم',
  muscle: 'عضلة',
  self: 'ذاتي',
  all: 'كل', fours: 'أربع',
  air: 'هوا',
  basic: 'أساسي',
  advanced: 'متقدم',
  intermediate: 'متوسط',
  modified: 'معدّل',
  negative: 'نزولي',
  isometric: 'ثابت',
  power: 'باور',
  speed: 'سرعة',
  quick: 'سريع',
  short: 'قصير',
  deep: 'عميق',
  big: 'كبير',
  greatest: 'أكبر',
  plus: 'زيادة',
  multiple: 'متعدد',
  sequence: 'تسلسل',
  range: 'مدى',
  style: 'ستايل',
  variation: 'تنويع',
  equipment: 'أداة',
  trainer: 'جهاز',
  ergometer: 'إرجومتر',
  elliptical: 'إليپتيكال',
  treadmill: 'مشّاية',
  stepmill: 'سلالم',
  stationary: 'ثابتة',
  ski: 'سكي', skier: 'متزلج',
  battling: 'قتال', ropes: 'حبال',
  yoga: 'يوغا',
  bicycle: 'عجلة', cycle: 'سيكل',
  clock: 'ساعة', clap: 'صفقة',
  diamond: 'ماس',
  contra: 'معاكس', contralateral: 'معاكس',
  internal: 'داخلي', external: 'خارجي',
  circular: 'دائري', circles: 'دوائر',
  rocking: 'تأرجح',
  drop: 'هبوط',
  flip: 'قلب',
  march: 'مشي عسكري',
  saw: 'منشار',
  slide: 'انزلاق',
  sprint: 'سبرنت', sprints: 'سبرنت',
  hop: 'نطة', hops: 'نطة',
  lean: 'ميل',
  reach: 'وصول',
  touch: 'لمس', touchers: 'لمس',
  tilt: 'إمالة',
  pelvic: 'حوض',
  posterior: 'خلفي',
  femoral: 'فخذي',
  peroneals: 'شظوية',
  tibialis: 'ظنبوب',
  rectus: 'مستقيمة', femoris: 'فخذية',
  piriformis: 'كمثرية',
  sternum: 'قص',
  major: 'كبرى',
  gluteus: 'أرداف',
  adductors: 'مقرِّبات',
  abductors: 'مبعِدات',
  inner: 'داخلي',
  outer: 'خارجي',
  neck: 'رقبة',
  face: 'وش',
  world: 'عالم',
  iron: 'حديد',
  tennis: 'تنس',
  hook: 'هوك',
  knife: 'سكينة',
  pirate: 'قرصان',
  prisoner: 'سجين',
  waiter: 'ويتر',
  farmer: 'فلاح', farmers: 'فلاح',
  monster: 'وحش',
  gorilla: 'غوريلا',
  bear: 'دب',
  cobra: 'كوبرا',
  sphinx: 'أبو الهول',
  cat: 'قطة',
  dog: 'كلب',
  skin: 'جلد',
  flag: 'علَم',
  jackknife: 'جاكنايف',
  wipers: 'مسّاحات',
  flutter: 'رفرفة',
  frankenstein: 'فرانكنشتاين',
  impossible: 'مستحيل',
  hyght: 'هايت',
  janda: 'جاندا',
  gironda: 'جيروندا',
  thibaudeau: 'ثيبودو',
  otis: 'أوتيس',
  tate: 'تيت',
  scott: 'سكوت',
  rocky: 'روكي',
  london: 'لندن',
  kayak: 'كاياك',
  cambered: 'مقوّس',
  captains: 'كابتن',
  curtsey: 'انحناء',
  cossack: 'قوزاق',
  svend: 'سفند',
  stalder: 'ستالدر',
  staircase: 'سلالم',
  star: 'نجمة',
  supper: 'سوبر',
  seesaw: 'سيسو',
  spell: 'رمي', caster: 'رمي',
  slingers: 'قاذف',
  stirrups: 'ركاب',
  squad: 'سكواد',
  astride: 'فتحة',
  forth: 'قدام وورا',
  bowling: 'بولينج',
  breeding: 'تربية',
  can: 'علبة',
  elevator: 'أسانسير',
  ground: 'أرض',
  pyramid: 'هرم',
  legged: 'أرجل',
  diagonal: 'مائل',
  anti: 'ضد',
  gravity: 'جاذبية',
  depth: 'عمق',
  figure: 'شكل',
  get: 'نهوض',
  kipping: 'كيبنج',
  mixed: 'مختلط',
  release: 'إفلات',
  catch: 'لقف',
  rotary: 'دوّار',
  unilateral: 'ناحية واحدة',
  pad: 'وسادة',
  pro: 'برو',
  middle: 'وسط',
  judo: 'جودو',
  basic: 'أساسي',
  ab: 'بطن',
  skierg: 'سكي إرج',
  speed: 'سرعة',
  pin: 'مثبّت',
  presses: 'ضغط',
  jefferson: 'جيفرسون',
  lifting: 'رفع',
  guillotine: 'مقصلة',
  both: 'الاتنين',
  under: 'تحت',
  knife: 'سكينة',
  bicycle: 'عجلة',
  board: 'لوح',
  pec: 'صدر',
  backward: 'ورا',
  apart: 'فتح',
  heel: 'كعب',
  touchers: 'لمس',
  all: 'كل',
  fours: 'أربع',
  squad: 'مجموعة',
  air: 'هوا',
  response: 'استجابة',
  point: 'نقطة',
  bottoms: 'قاع',
  fixed: 'ثابت',
  drag: 'سحب',
  jm: 'JM',
  y: 'Y',
  hug: 'حضن',
  off: 'من',
  world: 'دائري',
  iron: 'حديد',
  face: 'وش',
  deltoid: 'كتف',
  clasped: 'مضمومة',
  march: 'مارش',
  maltese: 'مالطي',
  kicks: 'ركل',
  flexion: 'ثني',
  tennis: 'تنس',
  potty: 'قعود',
  power: 'قوة',
  hyper: 'زائد',
  depresor: 'خافض',
  retractor: 'مقرِّب',
  sissy: 'سيسي',
  ski: 'سكي',
  spine: 'عمود',
  straddle: 'فتحة',
  three: 'تلاتة',
  ring: 'حلقة',
  saw: 'منشار',
  climb: 'تسلق',
  runners: 'جري',
  scissor: 'مقص',
  angle: 'زاوية',
  angled: 'مائل',
  semi: 'شبه',
  short: 'قصير',
  stride: 'خطوة',
  outstretched: 'ممدود',
  slide: 'انزلاق',
  hops: 'نطة',
  degrees: 'درجة',
  closer: 'أضيق',
  sprint: 'سبرنت',
  spell: 'رَمي',
  caster: 'قاذف',
  sphinx: 'أبو الهول',
  stalder: 'ستالدر',
  staircase: 'سلّم',
  strap: 'حزام',
  star: 'نجمة',
  outer: 'خارجي',
  abdominal: 'بطن',
  fallout: 'سقوط',
  swimmer: 'سباح',
  tire: 'كفر',
  trap: 'تراب',
  benches: 'بنش',
  twin: 'مزدوج',
  handle: 'مسكة',
  upward: 'لطالع',
  facing: 'مواجه',
  dog: 'كلب',
  elliptical: 'إليپتيكال',
  treadmill: 'مشّاية',
  stepmill: 'سلالم',
  cossack: 'قوزاق',
  round: 'لفّة',
  svend: 'سفند',
  wind: 'هوا',
  sprints: 'سبرنت',
  greatest: 'أكبر',
  rollerer: 'رولر',
  hack: 'هاك',
  neck: 'رقبة',
  attachment: 'وصلة',
  neutral: 'محايد',
  support: 'سند',
  lower: 'أسفل',
  bend: 'انحناء', bends: 'انحناء',
  throw: 'رمي',
  towel: 'فوطة',
  lift: 'رفع',
  palms: 'بطن الإيد',
  palm: 'بطن الإيد',
  inner: 'داخلي',
  elbow: 'كوع',
  spider: 'سبايدر',
  planche: 'بلانش',
  double: 'مزدوج',
  muscle: 'عضلة',
  suspended: 'معلّق',
  bike: 'عجلة',
  wheel: 'عجلة',
  stiff: 'قاسي',
  vertical: 'عمودي',
  stance: 'وقفة',
  female: '',
  sumo: 'سومو',
  adduction: 'تقريب',
  against: 'ضد',
  tap: 'لمسة',
  donkey: 'حمار',
  hand: 'إيد',
  flexor: 'ثناي',
  kick: 'ركلة',
  walk: 'مشي',
  hyperextension: 'مد زائد',
  hang: 'تعليق',
  jerk: 'جيرك',
  swing: 'مرجحة',
  abduction: 'تبعيد',
  bars: 'عقلة',
  walking: 'مشي',
  circles: 'دوائر',
  archer: 'رامي قوس',
  circular: 'دائري',
  calves: 'توأم',
  motion: 'حركة',
  quads: 'أمام الفخذ',
  underhand: 'من تحت',
  jack: 'جاك',
  internal: 'داخلي',
  drop: 'هبوط',
  burpee: 'بيربي',
  pose: 'وضع',
  range: 'مدى',
  external: 'خارجي',
  upper: 'أعلى',
  chair: 'كرسي',
  extended: 'ممدود',
  raised: 'مرفوع',
  arnold: 'أرنولد',
  french: 'فرنساوي',
  plyo: 'بلايوس',
  pike: 'بايك',
  frog: 'ضفدع',
  half: 'نص',
  oblique: 'جانب',
  scapula: 'لوح الكتف',
  windmill: 'طاحونة',
  flat: 'مسطح',
  pelvic: 'حوضي',
  tilt: 'إمالة',
  reach: 'وصول',
  self: 'ذاتي',
  '45°': '٤٥ درجة',
  slingers: 'قاذف',
  piriformis: 'كمثرية',
  jumps: 'قفز',
  balance: 'توازن',
  fixed: 'ثابت',
  horizontal: 'أفقي',
  pallof: 'بالوف',
  skull: 'سكل',
  drag: 'سحب',
  zercher: 'زرشر',
  jm: 'JM',
  romanian: 'روماني',
  bradford: 'برادفورد',
  rocky: 'روكي',
  rocking: 'تأرجح',
  thruster: 'ثراستر',
  crawl: 'زحف',
  bottoms: 'قاع',
  box: 'صندوق',
  mountain: 'جبل',
  climber: 'متسلق',
  pulley: 'بكرة',
  flip: 'قلب',
  rotational: 'دوراني',
  crossovers: 'كروس أوفر',
  tuck: 'تك',
  cage: 'قفص',
  trainer: 'جهاز',
  around: 'حوالين',
  stork: 'لقلاق',
  cuban: 'كوبي',
  finger: 'صباع',
  goblet: 'كأس',
  iron: 'حديد',
  face: 'وش',
  deltoid: 'كتف',
  pronation: 'كبّ',
  supination: 'قلب',
  world: 'دائري',
  hug: 'حضن',
  tennis: 'تنس',
  flexion: 'ثني',
  kicks: 'ركل',
  maltese: 'مالطي',
  march: 'مارش',
  clasped: 'مضمومة',
  handstand: 'وقوف على الإيدين',
  inchworm: 'دودة',
  isometric: 'ثابت',
  squeeze: 'عصر',
  pass: 'تمرير',
  pistol: 'فردي',
  landmine: 'لاندماين',
  gripless: 'من غير قبضة',
  point: 'نقطة',
  response: 'رد',
  slam: 'ضرب الأرض',
  modified: 'معدّل',
  olympic: 'أوليمبي',
  posterior: 'خلفي',
  potty: 'قعود',
  power: 'قوة',
  hyper: 'زائد',
  sissy: 'سيسي',
  ski: 'سكي',
  squats: 'سكوات',
  stationary: 'ثابتة',
  straddle: 'فتحة واسعة',
  three: 'تلاتة',
  one: 'واحد',
  two: 'اتنين',
  four: 'أربعة',
  keens: 'حماس',
  reps: 'عدّات',
  out: 'برّه',
  into: 'لجوه',
  plus: 'زيادة',
  quick: 'سريع',
  big: 'كبير',
  ring: 'حلقة',
  equipment: 'أداة',
  runners: 'عدّائين',
  scapular: 'لوح الكتف',
  scissor: 'مقص',
  angle: 'زاوية',
  sequence: 'تسلسل',
  semi: 'شبه',
  stride: 'خطوة واسعة',
  outstretched: 'ممدود',
  platform: 'منصة',
  slide: 'انزلاق',
  skater: 'متزلج',
  hops: 'نطة',
  ergometer: 'إرجومتر',
  skin: 'جلد',
  cat: 'قطة',
  closer: 'أضيق',
  angled: 'مائل',
  sledge: 'زلاجة',
  sprint: 'سبرنت',
  caster: 'قاذف',
  sphinx: 'أبو الهول',
  strap: 'حزام',
  star: 'نجمة',
  outer: 'خارجي',
  fallout: 'سقوط',
  swimmer: 'سباح',
  upward: 'لطالع',
  facing: 'مواجه',
  dog: 'كلب',
  round: 'لفّة',
  wind: 'هوا',
  sprints: 'سبرنت',
  drive: 'دفع',
  crossover: 'كروس أوفر',
  elevated: 'مرتفع',
  kayak: 'كاياك',
  cambered: 'مقوّس',
  clap: 'صفقة',
  clock: 'ساعة',
  cocoons: 'شرنقة',
  crab: 'كابوريا',
  curtsey: 'انحناء',
  cycle: 'سيكل',
  dead: 'ميت',
  bug: 'حشرة',
  deep: 'عميق',
  diamond: 'ماس',
  bowling: 'بولينج',
  contralateral: 'الجانب المعاكس',
  can: 'علبة',
  breeding: 'تربية',
  flyes: 'فتح',
  across: 'بالعرض',
  femoral: 'فخذي',
  pronated: 'كابّة',
  supinated: 'مقلوبة',
  pronate: 'كبّ',
  scott: 'سكوت',
  rotate: 'لف',
  carry: 'حمل',
  stepbox: 'ستيب بوكس',
  above: 'فوق',
  supported: 'مدعوم',
  tate: 'تيت',
  waiter: 'ويتر',
  dynamic: 'متحرك',
  elevator: 'أسانسير',
  ground: 'أرض',
  pyramid: 'هرم',
  ankles: 'كاحل',
  legged: 'أرجل',
  diagonal: 'مائل',
  anti: 'ضد',
  gravity: 'جاذبية',
  flag: 'علَم',
  flutter: 'رفرفة',
  frankenstein: 'فرانكنشتاين',
  gironda: 'جيروندا',
  sternum: 'قص',
  gorilla: 'غوريلا',
  groin: 'أعلى الفخذ',
  reversed: 'معكوس',
  hyght: 'هايت',
  impossible: 'مستحيل',
  depth: 'عمق',
  intermediate: 'متوسط',
  quad: 'أمام الفخذ',
  straps: 'أحزمة',
  wipers: 'مسّاحات',
  jackknife: 'جاكنايف',
  janda: 'جاندا',
  advanced: 'متقدم',
  renegade: 'رينيجيد',
  position: 'وضع',
  figure: 'شكل',
  pirate: 'قرصان',
  supper: 'سوبر',
  seesaw: 'سيسو',
  turkish: 'تركي',
  get: 'قوم',
  style: 'طريقة',
  kipping: 'كيبنج',
  korean: 'كوري',
  lean: 'ميل',
  left: 'شمال',
  hook: 'هوك',
  boxing: 'ملاكمة',
  gripper: 'قبّاض',
  overhand: 'من فوق',
  rotary: 'دوّار',
  pad: 'وسادة',
  unilateral: 'ناحية واحدة',
  london: 'لندن',
  catch: 'لقف',
  multiple: 'متعدد',
  release: 'إفلات',
  mixed: 'مختلط',
  hindu: 'هندي',
  monster: 'وحش',
  negative: 'نزولي',
  otis: 'أوتيس',
  outside: 'برا',
  peroneals: 'شظوية',
  cobra: 'كوبرا',
  tibialis: 'ظنبوب',
  prisoner: 'سجين',
  inside: 'جوا',
  plus: 'زيادة',
  quarter: 'ربع',
  feet: 'قدم',
  reclining: 'مائل للخلف',
  big: 'كبير',
  thrusts: 'دفع',
  thrust: 'دفع',
  ring: 'حلقة',
  climb: 'تسلق',
  blaster: 'بلاستر',
  russian: 'روسي',
  hamstring: 'خلف الفخذ',
  hack: 'هاك',
  inverse: 'معكوس',
  forward: 'قدام',
  attachment: 'وصلة',
  low: 'واطي',
  high: 'عالي',
  knee: 'ركبة',
  jump: 'قفز',
  bodyweight: 'وزن الجسم',
  full: 'كامل',
  shrug: 'رفع الكتف',
  bridge: 'كوبري',
  chin: 'ذقن',
  split: 'سبليت',
  clean: 'كلين',
  wall: 'حيط',
  medicine: 'ميدسن',
  head: 'راس',
  kickback: 'كيك باك',
  toe: 'صباع الرجل',
  parallel: 'متوازي',
  twisting: 'لف',
  rotation: 'دوران',
  plank: 'بلانك',
  pushdown: 'دفع لأسفل',
  lat: 'لاتس',
  hands: 'إيد',
  legs: 'رجلين',
  arms: 'ذراعين',
  touch: 'لمس',
  knees: 'ركبتين',
  dips: 'ديب',
  machine: 'ماكينة',
  roller: 'رولر',
  glute: 'أرداف',
  body: 'جسم',
  resistance: 'مقاومة',
  down: 'أسفل',
  rollerout: 'رول آوت',
  neck: 'رقبة',
  neutral: 'محايد',
  support: 'سند',
  bend: 'انحناء',
  throw: 'رمي',
  towel: 'فوطة',
  lift: 'رفع',
  snatch: 'خطف',
  revers: 'معكوس',
  bosu: 'بوسو',
  inner: 'داخلي',
  supine: 'على الظهر',
  elbow: 'كوع',
  planche: 'بلانش',
  inverted: 'مقلوب',
  double: 'مزدوج',
  muscle: 'عضلة',
  suspended: 'معلّق',
  '45': '٤٥',
}

const PHRASE_RE = PHRASES
  .map(([en, ar]) => [new RegExp('\\b' + en.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '\\b', 'g'), ar])

export function translateExName(name) {
  if (!name) return ''
  if (/[\u0600-\u06FF]/.test(name)) return name
  let s = String(name).toLowerCase().replace(/-/g, ' ')
  s = s.replace(/\b(male|female|pov)\b/g, ' ')
  for (const [re, ar] of PHRASE_RE) s = s.replace(re, ar)
  s = s.replace(/[a-z0-9°/]+/g, w => (Object.prototype.hasOwnProperty.call(WORDS, w) ? WORDS[w] : w))
  return s.replace(/\s+/g, ' ').replace(/\s+([،.,])/g, '$1').trim()
}
